#ifndef _MIPMAP_H
#define _MIPMAP_H

#include <gl/gl.h>

// Generated by mkproto
#ifdef EPSILON
#endif
#if defined(__WIN32__) && !defined(OPENSTEP)
void dummy(GLuint j, GLuint k);
#else
#endif
GLint gluBuild2DMipmapsSRC( GLenum target, GLenum dst_format, GLint width, GLint height, GLenum src_format, GLenum type, const void *data);
//GLint gluBuild2DMipmapsAlphaFade( GLenum target, GLint components, GLint width, GLint height, GLenum format, GLenum type, const void *data,F32 close_mix,F32 far_mix );
//GLint gluBuild2DMipmapsRGBFade( GLenum target, GLint components, GLint width, GLint height, GLenum format, GLenum type, unsigned char *data,F32 close_mix,F32 far_mix );

GLint gluBuild2DMipmapsRGBFadeInMem(GLint width, GLint height, GLenum format, GLenum type, const void *data,F32 close_mix,F32 far_mix );

// End mkproto
#endif
