Message
{
    MessageKey IDS_Q037Q046Q042fQ037s_remaining
    Scope "CrypticLauncher"
    DefaultString <&%.*f%s remaining&>
}

Message
{
    MessageKey IDS_Tried_connecting_Q037d_timesQ046
    Scope "CrypticLauncher"
    DefaultString <&Tried connecting %d times.&>
}

Message
{
    MessageKey IDS_Tried_connecting_1_timeQ046
    Scope "CrypticLauncher"
    DefaultString <&Tried connecting 1 time.&>
}

