Message
{
    MessageKey IDS_Success
    Scope "CrypticLauncher"
    DefaultString <&Success&>
}

Message
{
    MessageKey IDS_Current_transfer_queue_is_full
    Scope "CrypticLauncher"
    DefaultString <&Current transfer queue is full&>
}

Message
{
    MessageKey IDS_File_not_found
    Scope "CrypticLauncher"
    DefaultString <&File not found&>
}

Message
{
    MessageKey IDS_Unexpected_response_from_server
    Scope "CrypticLauncher"
    DefaultString <&Unexpected response from server&>
}

Message
{
    MessageKey IDS_Attempted_view_is_invalid
    Scope "CrypticLauncher"
    DefaultString <&Attempted view is invalid&>
}

Message
{
    MessageKey IDS_The_filespec_is_not_loaded
    Scope "CrypticLauncher"
    DefaultString <&The filespec is not loaded&>
}

Message
{
    MessageKey IDS_The_manifest_is_not_loaded
    Scope "CrypticLauncher"
    DefaultString <&The manifest is not loaded&>
}

Message
{
    MessageKey IDS_A_file_did_not_match_any_filespec
    Scope "CrypticLauncher"
    DefaultString <&A file did not match any filespec&>
}

Message
{
    MessageKey IDS_A_hogg_in_the_filespec_is_null
    Scope "CrypticLauncher"
    DefaultString <&A hogg in the filespec is null&>
}

Message
{
    MessageKey IDS_The_attempt_to_name_a_view_has_failed
    Scope "CrypticLauncher"
    DefaultString <&The attempt to name a view has failed&>
}

Message
{
    MessageKey IDS_The_attempt_to_set_an_author_has_failed
    Scope "CrypticLauncher"
    DefaultString <&The attempt to set an author has failed&>
}

Message
{
    MessageKey IDS_The_checkin_attempt_has_failed
    Scope "CrypticLauncher"
    DefaultString <&The checkin attempt has failed&>
}

Message
{
    MessageKey IDS_The_attempt_to_lock_a_file_has_failed
    Scope "CrypticLauncher"
    DefaultString <&The attempt to lock a file has failed&>
}

Message
{
    MessageKey IDS_The_connection_to_the_server_was_lost
    Scope "CrypticLauncher"
    DefaultString <&The connection to the server was lost&>
}

Message
{
    MessageKey IDS_The_client_is_currently_working_on_another_command
    Scope "CrypticLauncher"
    DefaultString <&The client is currently working on another command&>
}

Message
{
    MessageKey IDS_The_connection_was_idle_for_too_long
    Scope "CrypticLauncher"
    DefaultString <&The connection was idle for too long&>
}

Message
{
    MessageKey IDS_No_file_was_found_that_could_indicate_the_current_view
    Scope "CrypticLauncher"
    DefaultString <&No file was found that could indicate the current view&>
}

Message
{
    MessageKey IDS_Patch_DLL_not_loaded
    Scope "CrypticLauncher"
    DefaultString <&Patch DLL not loaded&>
}

Message
{
    MessageKey IDS_No_file_that_contains_connection_parameters_was_found
    Scope "CrypticLauncher"
    DefaultString <&No file that contains connection parameters was found&>
}

Message
{
    MessageKey IDS_A_dialog_box_was_passed_a_bad_message
    Scope "CrypticLauncher"
    DefaultString <&A dialog box was passed a bad message&>
}

Message
{
    MessageKey IDS_The_stored_header_for_the_file_is_not_up_to_date
    Scope "CrypticLauncher"
    DefaultString <&The stored header for the file is not up to date&>
}

Message
{
    MessageKey IDS_The_header_hogg_is_not_loaded
    Scope "CrypticLauncher"
    DefaultString <&The header hogg is not loaded&>
}

Message
{
    MessageKey IDS_The_requested_file_was_not_in_the_specified_root_folder
    Scope "CrypticLauncher"
    DefaultString <&The requested file was not in the specified root folder&>
}

Message
{
    MessageKey IDS_The_client_pointer_passed_in_for_the_patcher_was_null
    Scope "CrypticLauncher"
    DefaultString <&The client pointer passed in for the patcher was null&>
}

Message
{
    MessageKey IDS_No_error_string_was_found_for_some_other_errorQ044_and_you_looked_up_this_one_too
    Scope "CrypticLauncher"
    DefaultString <&No error string was found for some other error, and you looked up this one too&>
}

Message
{
    MessageKey IDS_Some_parameter_passed_into_a_patchclientlib_function_was_NULL
    Scope "CrypticLauncher"
    DefaultString <&Some parameter passed into a patchclientlib function was NULL&>
}

Message
{
    MessageKey IDS_The_buffer_provided_for_a_string_was_too_small
    Scope "CrypticLauncher"
    DefaultString <&The buffer provided for a string was too small&>
}

Message
{
    MessageKey IDS_The_specific_function_called_was_not_loaded_from_the_Patch_DLL
    Scope "CrypticLauncher"
    DefaultString <&The specific function called was not loaded from the Patch DLL&>
}

Message
{
    MessageKey IDS_The_net_comm_was_not_able_to_create_a_link_for_the_patcher
    Scope "CrypticLauncher"
    DefaultString <&The net comm was not able to create a link for the patcher&>
}

Message
{
    MessageKey IDS_The_patch_client_has_an_empty_manifest
    Scope "CrypticLauncher"
    DefaultString <&The patch client has an empty manifest&>
}

Message
{
    MessageKey IDS_A_hog_returned_an_error_while_trying_to_read
    Scope "CrypticLauncher"
    DefaultString <&A hog returned an error while trying to read&>
}

Message
{
    MessageKey IDS_A_locked_file_could_not_start_its_transfer
    Scope "CrypticLauncher"
    DefaultString <&A locked file could not start its transfer&>
}

Message
{
    MessageKey IDS_The_patchclient_got_a_message_while_it_was_in_a_state_with_no_response_function
    Scope "CrypticLauncher"
    DefaultString <&The patchclient got a message while it was in a state with no response function&>
}

Message
{
    MessageKey IDS_Some_parameter_passed_into_a_patchclientlib_function_was_found_to_be_invalid
    Scope "CrypticLauncher"
    DefaultString <&Some parameter passed into a patchclientlib function was found to be invalid&>
}

Message
{
    MessageKey IDS_The_programmer_screwed_up_somewhereQ044_and_something_that_shouldnQ039t_happen_did
    Scope "CrypticLauncher"
    DefaultString <&The programmer screwed up somewhere, and something that shouldn't happen did&>
}

Message
{
    MessageKey IDS_A_file_was_locked_that_could_not_be_open_for_writing
    Scope "CrypticLauncher"
    DefaultString <&A file was locked that could not be open for writing&>
}

Message
{
    MessageKey IDS_The_client_was_not_waiting_for_notification_from_the_server
    Scope "CrypticLauncher"
    DefaultString <&The client was not waiting for notification from the server&>
}

Message
{
    MessageKey IDS_The_hoggs_could_not_be_unloaded
    Scope "CrypticLauncher"
    DefaultString <&The hoggs could not be unloaded&>
}

Message
{
    MessageKey IDS_The_server_reports_that_the_client_sent_a_bad_packet_to_it
    Scope "CrypticLauncher"
    DefaultString <&The server reports that the client sent a bad packet to it&>
}

Message
{
    MessageKey IDS_The_xfer_has_been_destroyed
    Scope "CrypticLauncher"
    DefaultString <&The xfer has been destroyed&>
}

Message
{
    MessageKey IDS_The_operation_has_been_aborted
    Scope "CrypticLauncher"
    DefaultString <&The operation has been aborted&>
}

Message
{
    MessageKey IDS_No_error_string_was_found_for_the_specified_error
    Scope "CrypticLauncher"
    DefaultString <&No error string was found for the specified error&>
}

Message
{
    MessageKey IDS_OK
    Scope "CrypticLauncherNoDat"
    DefaultString <&OK&>
}

Message
{
    MessageKey IDS_Cancel
    Scope "CrypticLauncherNoDat"
    DefaultString <&Cancel&>
}

Message
{
    MessageKey IDS_Fullscreen
    Scope "CrypticLauncherNoDat"
    DefaultString <&Fullscreen&>
}

Message
{
    MessageKey IDS_Fast_launch
    Scope "CrypticLauncherNoDat"
    DefaultString <&Fast launch&>
}

Message
{
    MessageKey IDS_Safe_mode
    Scope "CrypticLauncherNoDat"
    DefaultString <&Safe mode&>
}

Message
{
    MessageKey IDS_Advanced_command_line
    Scope "CrypticLauncherNoDat"
    DefaultString <&Advanced command line&>
}

Message
{
    MessageKey IDS_Force_verify
    Scope "CrypticLauncherNoDat"
    DefaultString <&Force verify&>
}

Message
{
    MessageKey IDS_Language
    Scope "CrypticLauncherNoDat"
    DefaultString <&Language&>
}

Message
{
    MessageKey IDS_Minimize_to_tray
    Scope "CrypticLauncherNoDat"
    DefaultString <&Minimize to tray&>
}

Message
{
    MessageKey IDS_Show_tray_icon
    Scope "CrypticLauncherNoDat"
    DefaultString <&Show tray icon&>
}

Message
{
    MessageKey IDS_Proxy
    Scope "CrypticLauncherNoDat"
    DefaultString <&Proxy&>
}

Message
{
    MessageKey IDS_Show_all_games
    Scope "CrypticLauncherNoDat"
    DefaultString <&Show all games&>
}

Message
{
    MessageKey IDS_Patch_via_proxy
    Scope "CrypticLauncherNoDat"
    DefaultString <&Patch via proxy&>
}

Message
{
    MessageKey IDS_Disable_onQ045demand_patching
    Scope "CrypticLauncherNoDat"
    DefaultString <&Disable on-demand patching&>
}

Message
{
    MessageKey IDS_Options
    Scope "CrypticLauncherNoDat"
    DefaultString <&Options&>
}

Message
{
    MessageKey IDS_Cryptic_Launcher_Autoupdate
    Scope "CrypticLauncherNoDat"
    DefaultString <&Cryptic Launcher Autoupdate&>
}

Message
{
    MessageKey IDS_Trying_to_update_the_launcherQ046_Please_be_patientQ046
    Scope "CrypticLauncherNoDat"
    DefaultString <&Trying to update the launcher. Please be patient.&>
}

Message
{
    MessageKey IDS_MMORPG
    Scope "CrypticLauncherNoDat"
    DefaultString <&MMORPG&>
}

Message
{
    MessageKey IDS_Action
    Scope "CrypticLauncherNoDat"
    DefaultString <&Action&>
}

Message
{
    MessageKey IDS_Q034Never_RaGE_in_WinterQ034
    Scope "CrypticLauncherNoDat"
    DefaultString <&"Never RaGE in Winter"&>
}

Message
{
    MessageKey IDS_Ticket_parsing_failed
    Scope "CrypticLauncher"
    DefaultString <&Ticket parsing failed&>
}

Message
{
    MessageKey IDS_Account_server_connection_failed
    Scope "CrypticLauncher"
    DefaultString <&Account server connection failed&>
}

Message
{
    MessageKey IDS_User_authentication_failed
    Scope "CrypticLauncher"
    DefaultString <&User authentication failed&>
}

Message
{
    MessageKey IDS_Unknown_error
    Scope "CrypticLauncher"
    DefaultString <&Unknown error&>
}

Message
{
    MessageKey IDS_No_shards_were_found
    Scope "CrypticLauncher"
    DefaultString <&No shards were found&>
}

Message
{
    MessageKey IDS_Error_connecting_to_Account_Server
    Scope "CrypticLauncher"
    DefaultString <&Error connecting to Account Server&>
}

Message
{
    MessageKey IDS_Invalid_username_or_passwordQ046
    Scope "CrypticLauncher"
    DefaultString <&Invalid username or password.&>
}

Message
{
    MessageKey IDS_Too_many_attemptsQ059_please_try_again_laterQ046
    Scope "CrypticLauncher"
    DefaultString <&Too many attempts; please try again later.&>
}

Message
{
    MessageKey IDS_This_account_has_been_disabledQ046
    Scope "CrypticLauncher"
    DefaultString <&This account has been disabled.&>
}

Message
{
    MessageKey IDS_No_Cryptic_account_linked_to_Perfect_World_credentialsQ046
    Scope "CrypticLauncher"
    DefaultString <&No Cryptic account linked to Perfect World credentials.&>
}

Message
{
    MessageKey IDS_Please_log_in_using_your_Perfect_World_account_nameQ046
    Scope "CrypticLauncher"
    DefaultString <&Please log in using your Perfect World account name.&>
}

Message
{
    MessageKey IDS_This_account_has_been_bannedQ046
    Scope "CrypticLauncher"
    DefaultString <&This account has been banned.&>
}

Message
{
    MessageKey IDS_This_account_must_be_linked_to_a_Perfect_World_account_to_log_inQ046
    Scope "CrypticLauncher"
    DefaultString <&This account must be linked to a Perfect World account to log in.&>
}

Message
{
    MessageKey IDS_Invalid_username
    Scope "CrypticLauncher"
    DefaultString <&Invalid username&>
}

Message
{
    MessageKey IDS_Invalid_password
    Scope "CrypticLauncher"
    DefaultString <&Invalid password&>
}

Message
{
    MessageKey IDS_CouldnQ039t_even_attempt_account_server_connection
    Scope "CrypticLauncher"
    DefaultString <&Couldn't even attempt account server connection&>
}

Message
{
    MessageKey IDS_Lost_connection_to_Account_Server
    Scope "CrypticLauncher"
    DefaultString <&Lost connection to Account Server&>
}

