Message
{
    MessageKey IDS_Unable_to_contact_account_server
    Scope "CrypticLauncher"
    DefaultString <&Unable to contact account server&>
}

Message
{
    MessageKey IDS_DNS_canQ039t_resolve_controller_tracker
    Scope "CrypticLauncher"
    DefaultString <&DNS can't resolve controller tracker&>
}

Message
{
    MessageKey IDS_Attempting_to_connect_to_controller_tracker
    Scope "CrypticLauncher"
    DefaultString <&Attempting to connect to controller tracker&>
}

