#ifndef _FILE_H
#define _FILE_H

#include <stdio.h>
#include <io.h>
#include "memcheck.h"

#define sfread fread
#define fileClose fclose

#if USEZLIB
#define FILE void
#undef getc
#define getc x_getc
#define fseek x_fseek
#define fopen x_fopen
#define fclose x_fclose
#define ftell x_ftell
#define fread x_fread
#define fwrite x_fwrite
#define fgets x_fgets
#define fprintf x_fprintf
#define fflush x_fflush
#define fscanf x_fscanf

#define FW_ALLOC_STACK_SIZE 4096
typedef struct
{
	void	*fptr;
	int		gzio;
	char	name[256];
#ifdef FW_TRACK_ALLOCATION
	char	allocStack[FW_ALLOC_STACK_SIZE];	// Who allocated me?
#endif
} FileWrapper;

#else
#include "stdio.h"
#endif

#define fileAlloc(fname,lenp) fileAlloc_dbg(fname,lenp MEM_DBG_PARMS_INIT)

typedef enum{
	FSA_NO_EXPLORE_DIRECTORY,
	FSA_EXPLORE_DIRECTORY,
	FSA_STOP
} FileScanAction;
typedef FileScanAction (*FileScanProcessor)(char* dir, struct _finddata_t* data);

typedef struct FileScanContext FileScanContext;
typedef FileScanAction (*FileScanProcessorEx)(FileScanContext* context);
struct FileScanContext{
	FileScanProcessorEx processor;
	char* dir;
	struct _finddata_t* fileInfo;
};

// Generated by mkproto
void fileLoadGameDataDir(int load);
int fileAddSearchPath(char* path);
char *fileDataDir();
char *fileTempDir();
char *fileSrcDir();
char *fileFixSlashes(char *str);
char *fileLocate(char *fname);
char *fileLocateExists(char *fname);
FILE *fileOpen(char *fname,char *how);
FILE *fileOpenEx(const char *fnameFormat, char *how, ...);
FILE *fileOpenTemp(char *fname,char *how);
void fileFree(void *mem);
char **fileScanDirRecurse(char *dir,int *count_ptr);
char **fileScanDir(char *dir,int *count_ptr);
void fileScanDirFreeNames(char **names,int count);
void fileScanDirRecurseEx(char* dir, FileScanProcessor processor);
void fileScanDirRecurseContext(char* dir, FileScanContext* context);
FileScanAction printAllFileNames(char* dir, struct _finddata_t* data);
void *fileAlloc_dbg(char *fname,int *lenp MEM_DBG_PARMS);
#if USEZLIB
void *x_fopen(char *name,char *how);
int x_fclose(FileWrapper *fw);
int x_fseek(FileWrapper *fw,long dist,int whence);
int x_getc(FileWrapper *fw);
long x_ftell(FileWrapper *fw);
long x_fread(void *buf,long size1,long size2,FileWrapper *fw);
long x_fwrite(const void *buf,long size1,long size2,FileWrapper *fw);
char *x_fgets(char *buf,int len,FileWrapper *fw);
void x_fflush(FileWrapper *fw);
int x_fprintf (FileWrapper *fw, const char *format, ...);
int x_fscanf(FileWrapper* fw, const char* format, ...);
#endif
FILE *fileGetStdout();
#ifdef USEZLIB
void *fileRealPointer(FileWrapper *fw);
#else
void *fileRealPointer(FILE *file);
#endif
void fileOpenFiles();
char *fileLocateQuick(char * fname);
#ifdef USEZLIB
FILE* fileDup(FileWrapper* file, char* mode);
#endif

// End mkproto

#endif
