#ifndef _UTILS_H
#define _UTILS_H

#include <stdio.h>
#include "stdtypes.h"

#define SETB(mem,bitnum) ((mem)[(bitnum) >> 5] |= (1 << ((bitnum) & 31)))
#define CLRB(mem,bitnum) ((mem)[(bitnum) >> 5] &= ~(1 << ((bitnum) & 31)))
#define TSTB(mem,bitnum) ((mem)[(bitnum) >> 5] & (1 << ((bitnum) & 31)))

#ifdef WIN32
	#define strcasecmp(a,b) _stricmp(a,b)
#else
	int strcasecmp(const char *a,const char *b);
#endif

// Generated by mkproto
int fileNewer(char *refname,char *testname);
U32 fileLastChanged(char *refname);
void forwardSlashes(char *path);
void backSlashes(char *path);
void concatpath(char *s1,char *s2,char *full);
void setgamedir(char *fname,char *dirname,char *newfname);
void makefullpath(char *dir,char *full);
void mkdirtree(char *path);
void rmdirtree(char *path);
int makeDirectories(char* dirPath);
char *strtok_r(char *target,const char *delim,char **last);
char* strsep2(char** str, const char* delim, char* retrievedDelim);
char* strsep(char** str, const char* delim);
#ifndef strcasecmp
int strcasecmp(const char *a,const char *b);
#endif
int strncasecmp(const char *a,const char *b,int n);
char *strstri(char *s,char *srch);
char *fileLoadSize(char *fname,unsigned long *size);
char *fileLoad(char *fname);
int fileSize(char *fname);
int fileExists(char *fname);
int dirExists(char *dirname);
int tokenize_line(char *buf,char *args[],char **next_line_ptr);
int system_detach(char *cmd);
void *dynArrayAdd(void **basep,int struct_size,int *count,int *max_count,int num_structs);
void *dynArrayAddp(void ***basep,int *count,int *max_count,void *ptr);
void *dynArrayFit(void **basep,int struct_size,int *count_ptr,int *max_count,int idx_to_fit);
void newConsoleWindow();
void setConsoleTitle(char *msg);
char *getFileName(char *fname);
char *getDirectoryName(char *fullPath);
char *getUserName();
// End mkproto
#endif
