// Auto-generated by GenerateBundledModtimes.py
#pragma once
#define MODTIME_CRYPTICERROR 1423852082 // from OS (gimme-controlled location)
#define MODTIME_DBGHELP 1381705060 // from OS (gimme-controlled location)
#define MODTIME_LIBCEF 0x523CDFAD // from COFF
#define MODTIME_AVCODEC 0x4FDA7C96 // from COFF
#define MODTIME_AVFORMAT 0x4FDA7C93 // from COFF
#define MODTIME_AVUTIL 0x4FDA7C6C // from COFF
#define MODTIME_ICUDT 0x4F29DD80 // from COFF
