// This header file contains configuration for the infrastructure environment that the CrypticLauncher relies on.

#pragma once

#include "Organization.h"

#define LAUNCHER_WEB_PROTOCOL_VERSION			"1"
#define LAUNCHER_URL_WEB_PROTOCOL_VERSION_STR	"?version=" LAUNCHER_WEB_PROTOCOL_VERSION

#define ENV_US_CONTROLLERTRACKER_HOST		ORGANIZATION_DOMAIN
// US Acct Server Host comes from DEFAULT_LATELINK_getAccountServer() in accountnet.c
#define ENV_US_CHAMPIONS_LAUNCHER_URL		"http://" ORGANIZATION_DOMAIN
#define ENV_US_STO_LAUNCHER_URL				"http://" ORGANIZATION_DOMAIN
#define ENV_US_NW_LAUNCHER_URL				"http://" ORGANIZATION_DOMAIN

// Internal QA environment, -qa
#define ENV_QA_CONTROLLERTRACKER_HOST		ORGANIZATION_DOMAIN
#define ENV_QA_ACCOUNTSERVER_HOST			ORGANIZATION_DOMAIN
#define ENV_QA_CHAMPIONS_LAUNCHER_URL		"http://" ORGANIZATION_DOMAIN
#define ENV_QA_STO_LAUNCHER_URL				"http://" ORGANIZATION_DOMAIN
#define ENV_QA_NW_LAUNCHER_URL				"http://" ORGANIZATION_DOMAIN

// Internal Dev environment, -dev
#define ENV_DEV_CONTROLLERTRACKER_HOST		ORGANIZATION_DOMAIN
#define ENV_DEV_ACCOUNTSERVER_HOST			ORGANIZATION_DOMAIN
#define ENV_DEV_CHAMPIONS_LAUNCHER_URL		"http://" ORGANIZATION_DOMAIN
#define ENV_DEV_STO_LAUNCHER_URL			"http://" ORGANIZATION_DOMAIN
#define ENV_DEV_NW_LAUNCHER_URL				"http://" ORGANIZATION_DOMAIN

// External PW China environment, -pwrd
#define ENV_PWRD_CONTROLLERTRACKER_HOST		ORGANIZATION_DOMAIN
#define ENV_PWRD_ACCOUNTSERVER_HOST			ORGANIZATION_DOMAIN
#define ENV_PWRD_LAUNCHER_URL				"http://" ORGANIZATION_DOMAIN "/"
#define ENV_PWRD_PATCH_SERVER_HOST			ORGANIZATION_DOMAIN

// External PW Taiwan environment, -pwt
#define ENV_PWT_CONTROLLERTRACKER_HOST		ORGANIZATION_DOMAIN
#define ENV_PWT_ACCOUNTSERVER_HOST			ORGANIZATION_DOMAIN
#define ENV_PWT_LAUNCHER_URL				"http://" ORGANIZATION_DOMAIN "/"
#define ENV_PWT_PATCH_SERVER_HOST			ORGANIZATION_DOMAIN

#define ENV_US_PROXY_HOST					ORGANIZATION_DOMAIN
#define ENV_EU1_PROXY_HOST					ORGANIZATION_DOMAIN
#define ENV_EU2_PROXY_HOST					ORGANIZATION_DOMAIN

#define ENV_US_PATCH_SERVER_HOST			ORGANIZATION_DOMAIN

#define SHARD_CATEGORY_LIVE					"Live"
#define SHARD_CATEGORY_AVATAR				"Avatar" // This is not actively used
#define SHARD_CATEGORY_XBOX					"Xbox" // This is not actively used
#define SHARD_CATEGORY_PLAYTEST				"Playtest"
#define SHARD_CATEGORY_BETA					"Beta"