import os
import re
import shlex
from subprocess import Popen, PIPE

def coffTimestamp(filepath):
	cmd = "dumpbin /headers " + filepath
	process = Popen(shlex.split(cmd), stdout=PIPE)
	output = process.communicate()[0]
	exit_code = process.wait()
	return "0x" + re.search(r'([0-9A-F]+)\s+time', output, re.MULTILINE).group(1)

header = open('bundled_modtimes.h', 'w')
header.write('// Auto-generated by GenerateBundledModtimes.py\n')
header.write('#pragma once\n')

# note that CrypticError.exe and dbghelp.dll come from a gimme controlled directory, so their os timestamps are accurate
header.write('#define MODTIME_CRYPTICERROR %u // from OS (gimme-controlled location)\n'%os.stat('C:/Night/tools/bin/CrypticError.exe').st_mtime)
header.write('#define MODTIME_DBGHELP %u // from OS (gimme-controlled location)\n'%os.stat('C:/Night/tools/bin/dbghelp.dll').st_mtime)

# note that libcef related dll's come from SVN, and their timestamps do not reflect an accurate build time.  we use dumpbin to get them.
header.write('#define MODTIME_LIBCEF %s // from COFF\n'%coffTimestamp('../bin/libcef.dll'))
header.write('#define MODTIME_AVCODEC %s // from COFF\n'%coffTimestamp('../bin/avcodec-54.dll'))
header.write('#define MODTIME_AVFORMAT %s // from COFF\n'%coffTimestamp('../bin/avformat-54.dll'))
header.write('#define MODTIME_AVUTIL %s // from COFF\n'%coffTimestamp('../bin/avutil-51.dll'))
header.write('#define MODTIME_ICUDT %s // from COFF\n'%coffTimestamp('../bin/icudt.dll'))

header.close()

exit()

