// Autogenerated by GenerateVersion.bat 
#define BUILD_YEAR 2015 
#define BUILD_MONTH 02 
#define BUILD_DAY 14 
#define BUILD_HOUR 01 
#define BUILD_MINUTE 50 
#define BUILD_TIME 0150 
#define BUILD_VERSIONSTAMP "2015, 02, 14, 0150" 
#define BUILD_TIMESTAMP "2015-02-14_01:50" 
#define BUILD_CRYPTICSTAMP "CL_2015_02_14_01_50" 
