//This file contains data and prototypes for autoruns. It is autogenerated by StructParser

// autogeneratednocheckin
//This file contains data and prototypes for autoruns. It is autogenerated by StructParser

// autogeneratednocheckin
#include"metatask.h"
extern int giCurAutoRunStep;
extern void Add_Auto_Cmds_NNOAppServer(void);
extern void Add_Auto_Cmds_NNOAppServer_Later(void); extern void OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup(void); extern void OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame(void); extern void RegisterProjectVars(void); extern void _NNOAppServer_AutoRun_SPECIALINTERNAL(void);
void doAutoRuns_AppServerLib_0(void);
void doAutoRuns_AppServerLib_1(void);
void doAutoRuns_AppServerLib_2(void);
void doAutoRuns_AppServerLib_3(void);
void doAutoRuns_AppServerLib_4(void);
void doAutoRuns_AppServerLib_5(void);
void doAutoRuns_AppServerLib_6(void);
void doAutoRuns_AppServerLib_7(void);
void doAutoRuns_ContentLib_0(void);
void doAutoRuns_ContentLib_1(void);
void doAutoRuns_ContentLib_2(void);
void doAutoRuns_ContentLib_3(void);
void doAutoRuns_ContentLib_4(void);
void doAutoRuns_ContentLib_5(void);
void doAutoRuns_ContentLib_6(void);
void doAutoRuns_ContentLib_7(void);
void doAutoRuns_HttpLib_0(void);
void doAutoRuns_HttpLib_1(void);
void doAutoRuns_HttpLib_2(void);
void doAutoRuns_HttpLib_3(void);
void doAutoRuns_HttpLib_4(void);
void doAutoRuns_HttpLib_5(void);
void doAutoRuns_HttpLib_6(void);
void doAutoRuns_HttpLib_7(void);
void doAutoRuns_PatchClientLib_0(void);
void doAutoRuns_PatchClientLib_1(void);
void doAutoRuns_PatchClientLib_2(void);
void doAutoRuns_PatchClientLib_3(void);
void doAutoRuns_PatchClientLib_4(void);
void doAutoRuns_PatchClientLib_5(void);
void doAutoRuns_PatchClientLib_6(void);
void doAutoRuns_PatchClientLib_7(void);
void doAutoRuns_ServerLib_0(void);
void doAutoRuns_ServerLib_1(void);
void doAutoRuns_ServerLib_2(void);
void doAutoRuns_ServerLib_3(void);
void doAutoRuns_ServerLib_4(void);
void doAutoRuns_ServerLib_5(void);
void doAutoRuns_ServerLib_6(void);
void doAutoRuns_ServerLib_7(void);
void doAutoRuns_UtilitiesLib_0(void);
void doAutoRuns_UtilitiesLib_1(void);
void doAutoRuns_UtilitiesLib_2(void);
void doAutoRuns_UtilitiesLib_3(void);
void doAutoRuns_UtilitiesLib_4(void);
void doAutoRuns_UtilitiesLib_5(void);
void doAutoRuns_UtilitiesLib_6(void);
void doAutoRuns_UtilitiesLib_7(void);
void doAutoRuns_WorldLib_0(void);
void doAutoRuns_WorldLib_1(void);
void doAutoRuns_WorldLib_2(void);
void doAutoRuns_WorldLib_3(void);
void doAutoRuns_WorldLib_4(void);
void doAutoRuns_WorldLib_5(void);
void doAutoRuns_WorldLib_6(void);
void doAutoRuns_WorldLib_7(void);

void doAutoRuns_NNOAppServer_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 0;
	doAutoRuns_AppServerLib_0();
	doAutoRuns_ContentLib_0();
	doAutoRuns_HttpLib_0();
	doAutoRuns_PatchClientLib_0();
	doAutoRuns_ServerLib_0();
	doAutoRuns_UtilitiesLib_0();
	doAutoRuns_WorldLib_0();
	RegisterProjectVars();
	_NNOAppServer_AutoRun_SPECIALINTERNAL(); }

void doAutoRuns_NNOAppServer_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 1;
	doAutoRuns_AppServerLib_1();
	doAutoRuns_ContentLib_1();
	doAutoRuns_HttpLib_1();
	doAutoRuns_PatchClientLib_1();
	doAutoRuns_ServerLib_1();
	doAutoRuns_UtilitiesLib_1();
	doAutoRuns_WorldLib_1();
	OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup();
	OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame(); }

void doAutoRuns_NNOAppServer_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 2;
	doAutoRuns_AppServerLib_2();
	doAutoRuns_ContentLib_2();
	doAutoRuns_HttpLib_2();
	doAutoRuns_PatchClientLib_2();
	doAutoRuns_ServerLib_2();
	doAutoRuns_UtilitiesLib_2();
	doAutoRuns_WorldLib_2();
	Add_Auto_Cmds_NNOAppServer();
}

void doAutoRuns_NNOAppServer_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 3;
	doAutoRuns_AppServerLib_3();
	doAutoRuns_ContentLib_3();
	doAutoRuns_HttpLib_3();
	doAutoRuns_PatchClientLib_3();
	doAutoRuns_ServerLib_3();
	doAutoRuns_UtilitiesLib_3();
	doAutoRuns_WorldLib_3();
}

void doAutoRuns_NNOAppServer_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 4;
	doAutoRuns_AppServerLib_4();
	doAutoRuns_ContentLib_4();
	doAutoRuns_HttpLib_4();
	doAutoRuns_PatchClientLib_4();
	doAutoRuns_ServerLib_4();
	doAutoRuns_UtilitiesLib_4();
	doAutoRuns_WorldLib_4();
	Add_Auto_Cmds_NNOAppServer_Later();
}

void doAutoRuns_NNOAppServer_5(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 5;
	doAutoRuns_AppServerLib_5();
	doAutoRuns_ContentLib_5();
	doAutoRuns_HttpLib_5();
	doAutoRuns_PatchClientLib_5();
	doAutoRuns_ServerLib_5();
	doAutoRuns_UtilitiesLib_5();
	doAutoRuns_WorldLib_5();
}

void doAutoRuns_NNOAppServer_6(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 6;
	doAutoRuns_AppServerLib_6();
	doAutoRuns_ContentLib_6();
	doAutoRuns_HttpLib_6();
	doAutoRuns_PatchClientLib_6();
	doAutoRuns_ServerLib_6();
	doAutoRuns_UtilitiesLib_6();
	doAutoRuns_WorldLib_6();
}

void doAutoRuns_NNOAppServer_7(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 7;
	doAutoRuns_AppServerLib_7();
	doAutoRuns_ContentLib_7();
	doAutoRuns_HttpLib_7();
	doAutoRuns_PatchClientLib_7();
	doAutoRuns_ServerLib_7();
	doAutoRuns_UtilitiesLib_7();
	doAutoRuns_WorldLib_7();
}
extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_NNOAppServer(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_NNOAppServer_0();
	doAutoRuns_NNOAppServer_1();
	doAutoRuns_NNOAppServer_2();
	doAutoRuns_NNOAppServer_3();
	doAutoRuns_NNOAppServer_4();
	doAutoRuns_NNOAppServer_5();
	doAutoRuns_NNOAppServer_6();
	return 0;
}
int MagicAutoRunFunc_File_NNOAppServer(void)
{
	doAutoRuns_NNOAppServer_7();
	return 0;
}
void do_auto_runs(void)
{
	MagicAutoRunFunc_NNOAppServer();
}
void do_auto_runs_file(void)
{
	MagicAutoRunFunc_File_NNOAppServer();
}
extern void _AppServerLib_AutoRun_SPECIALINTERNAL(void);
extern void _ContentLib_AutoRun_SPECIALINTERNAL(void);
extern void _HttpLib_AutoRun_SPECIALINTERNAL(void);
extern void _PatchClientLib_AutoRun_SPECIALINTERNAL(void);
extern void _ServerLib_AutoRun_SPECIALINTERNAL(void);
extern void _UtilitiesLib_AutoRun_SPECIALINTERNAL(void);
extern void _WorldLib_AutoRun_SPECIALINTERNAL(void);
void do_special_internal_autoruns(void)
{
	_NNOAppServer_AutoRun_SPECIALINTERNAL();
	_AppServerLib_AutoRun_SPECIALINTERNAL();
	_ContentLib_AutoRun_SPECIALINTERNAL();
	_HttpLib_AutoRun_SPECIALINTERNAL();
	_PatchClientLib_AutoRun_SPECIALINTERNAL();
	_ServerLib_AutoRun_SPECIALINTERNAL();
	_UtilitiesLib_AutoRun_SPECIALINTERNAL();
	_WorldLib_AutoRun_SPECIALINTERNAL();
};


#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
6
"Add_Auto_Cmds_NNOAppServer" "autogen_magiccommands" 2 "" ""  "" "" 0  0 
"Add_Auto_Cmds_NNOAppServer_Later" "autogen_magiccommands" 4 "" ""  "" "" 0  0 
"OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup" "C:\src\Night\AppServer\..\Common\NNOCommon.c" 1 "" ""  "" "" 0  0 
"OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame" "C:\src\Night\AppServer\..\Common\NNOCommon.c" 1 "" ""  "" "" 0  0 
"RegisterProjectVars" "C:\src\Night\AppServer\..\Common\NNOCommon.c" 0 "" ""  "" "" 0  0 
"_NNOAppServer_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" ""  "" "" 0  0 
#endif
