//autogeneratednocheckin  this file is autogenerated by structparser
#pragma warning(default:4242)
#ifdef WANT_EXPRCODE_ENUMS_NNOAPPSERVER
#define WANT_EXPRCODE_ENUMS_APPSERVERLIB 1
#include "..\..\CrossRoads\AppServerLib\autogen\AppServerLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_APPSERVERLIB
#define WANT_EXPRCODE_ENUMS_CONTENTLIB 1
#include "..\..\libs\ContentLib\autogen\ContentLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_CONTENTLIB
#define WANT_EXPRCODE_ENUMS_HTTPLIB 1
#include "..\..\libs\HttpLib\autogen\HttpLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_HTTPLIB
#define WANT_EXPRCODE_ENUMS_PATCHCLIENTLIB 1
#include "..\..\libs\PatchClientLib\autogen\PatchClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_PATCHCLIENTLIB
#define WANT_EXPRCODE_ENUMS_SERVERLIB 1
#include "..\..\libs\ServerLib\autogen\ServerLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_SERVERLIB
#define WANT_EXPRCODE_ENUMS_UTILITIESLIB 1
#include "..\..\libs\UtilitiesLib\autogen\UtilitiesLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_UTILITIESLIB
#define WANT_EXPRCODE_ENUMS_WORLDLIB 1
#include "..\..\libs\WorldLib\autogen\WorldLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_WORLDLIB
#endif //WANT_EXPRCODE_ENUMS_NNOAPPSERVER
#ifdef WANT_EXPRCODE_STATICDEFINE_NNOAPPSERVER
#define WANT_EXPRCODE_STATICDEFINE_APPSERVERLIB 1
#include "..\..\CrossRoads\AppServerLib\autogen\AppServerLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_APPSERVERLIB
#define WANT_EXPRCODE_STATICDEFINE_CONTENTLIB 1
#include "..\..\libs\ContentLib\autogen\ContentLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_CONTENTLIB
#define WANT_EXPRCODE_STATICDEFINE_HTTPLIB 1
#include "..\..\libs\HttpLib\autogen\HttpLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_HTTPLIB
#define WANT_EXPRCODE_STATICDEFINE_PATCHCLIENTLIB 1
#include "..\..\libs\PatchClientLib\autogen\PatchClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_PATCHCLIENTLIB
#define WANT_EXPRCODE_STATICDEFINE_SERVERLIB 1
#include "..\..\libs\ServerLib\autogen\ServerLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_SERVERLIB
#define WANT_EXPRCODE_STATICDEFINE_UTILITIESLIB 1
#include "..\..\libs\UtilitiesLib\autogen\UtilitiesLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_UTILITIESLIB
#define WANT_EXPRCODE_STATICDEFINE_WORLDLIB 1
#include "..\..\libs\WorldLib\autogen\WorldLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_WORLDLIB
#endif //WANT_EXPRCODE_STATICDEFINE_NNOAPPSERVER
#ifdef WANT_EXPRCODE_PROTOTYPES_NNOAPPSERVER
#define WANT_EXPRCODE_PROTOTYPES_APPSERVERLIB 1
#include "..\..\CrossRoads\AppServerLib\autogen\AppServerLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_APPSERVERLIB
#define WANT_EXPRCODE_PROTOTYPES_CONTENTLIB 1
#include "..\..\libs\ContentLib\autogen\ContentLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_CONTENTLIB
#define WANT_EXPRCODE_PROTOTYPES_HTTPLIB 1
#include "..\..\libs\HttpLib\autogen\HttpLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_HTTPLIB
#define WANT_EXPRCODE_PROTOTYPES_PATCHCLIENTLIB 1
#include "..\..\libs\PatchClientLib\autogen\PatchClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_PATCHCLIENTLIB
#define WANT_EXPRCODE_PROTOTYPES_SERVERLIB 1
#include "..\..\libs\ServerLib\autogen\ServerLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_SERVERLIB
#define WANT_EXPRCODE_PROTOTYPES_UTILITIESLIB 1
#include "..\..\libs\UtilitiesLib\autogen\UtilitiesLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_UTILITIESLIB
#define WANT_EXPRCODE_PROTOTYPES_WORLDLIB 1
#include "..\..\libs\WorldLib\autogen\WorldLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_WORLDLIB
#endif // WANT_EXPRCODE_PROTOTYPES_NNOAPPSERVER
#ifdef WANT_EXPRCODE_SWITCH_CASES_NNOAPPSERVER
#define WANT_EXPRCODE_SWITCH_CASES_APPSERVERLIB 1
#include "..\..\CrossRoads\AppServerLib\autogen\AppServerLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_APPSERVERLIB
#define WANT_EXPRCODE_SWITCH_CASES_CONTENTLIB 1
#include "..\..\libs\ContentLib\autogen\ContentLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_CONTENTLIB
#define WANT_EXPRCODE_SWITCH_CASES_HTTPLIB 1
#include "..\..\libs\HttpLib\autogen\HttpLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_HTTPLIB
#define WANT_EXPRCODE_SWITCH_CASES_PATCHCLIENTLIB 1
#include "..\..\libs\PatchClientLib\autogen\PatchClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_PATCHCLIENTLIB
#define WANT_EXPRCODE_SWITCH_CASES_SERVERLIB 1
#include "..\..\libs\ServerLib\autogen\ServerLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_SERVERLIB
#define WANT_EXPRCODE_SWITCH_CASES_UTILITIESLIB 1
#include "..\..\libs\UtilitiesLib\autogen\UtilitiesLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_UTILITIESLIB
#define WANT_EXPRCODE_SWITCH_CASES_WORLDLIB 1
#include "..\..\libs\WorldLib\autogen\WorldLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_WORLDLIB
#endif // WANT_EXPRCODE_SWITCH_CASES_NNOAPPSERVER
