//This file is autogenerated. It contains functions to call all AUTO_COMMANDS
//from the NNOGameClient project. autogeneratednocheckin
#include "ClientControllerLib.h"
#ifndef CMD_DECLSPEC
#define CMD_DECLSPEC
#endif
