//This file contains data and prototypes for autoruns. It is autogenerated by StructParser

// autogeneratednocheckin
//This file contains data and prototypes for autoruns. It is autogenerated by StructParser

// autogeneratednocheckin
#include"metatask.h"
extern int giCurAutoRunStep;
extern void Add_Auto_Cmds_NNOGameClient(void);
extern void Add_Auto_Cmds_NNOGameClient_Later(void); extern void InitGlobalConfig(void); extern void OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup(void); extern void OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame(void); extern void OVERRIDE_LATELINK_AUTORUN_schemes_ControlSchemeOptionInit(void);
extern void OverrideConfig(void); extern void RegisterProjectVars(void); extern void _NNOGameClient_AutoRun_SPECIALINTERNAL(void); void doAutoRuns_GameClientLib_0(void);
void doAutoRuns_GameClientLib_1(void);
void doAutoRuns_GameClientLib_2(void);
void doAutoRuns_GameClientLib_3(void);
void doAutoRuns_GameClientLib_4(void);
void doAutoRuns_GameClientLib_5(void);
void doAutoRuns_GameClientLib_6(void);
void doAutoRuns_GameClientLib_7(void);
void doAutoRuns_ContentLib_0(void);
void doAutoRuns_ContentLib_1(void);
void doAutoRuns_ContentLib_2(void);
void doAutoRuns_ContentLib_3(void);
void doAutoRuns_ContentLib_4(void);
void doAutoRuns_ContentLib_5(void);
void doAutoRuns_ContentLib_6(void);
void doAutoRuns_ContentLib_7(void);
void doAutoRuns_GraphicsLib_0(void);
void doAutoRuns_GraphicsLib_1(void);
void doAutoRuns_GraphicsLib_2(void);
void doAutoRuns_GraphicsLib_3(void);
void doAutoRuns_GraphicsLib_4(void);
void doAutoRuns_GraphicsLib_5(void);
void doAutoRuns_GraphicsLib_6(void);
void doAutoRuns_GraphicsLib_7(void);
void doAutoRuns_HttpLib_0(void);
void doAutoRuns_HttpLib_1(void);
void doAutoRuns_HttpLib_2(void);
void doAutoRuns_HttpLib_3(void);
void doAutoRuns_HttpLib_4(void);
void doAutoRuns_HttpLib_5(void);
void doAutoRuns_HttpLib_6(void);
void doAutoRuns_HttpLib_7(void);
void doAutoRuns_InputLib_0(void);
void doAutoRuns_InputLib_1(void);
void doAutoRuns_InputLib_2(void);
void doAutoRuns_InputLib_3(void);
void doAutoRuns_InputLib_4(void);
void doAutoRuns_InputLib_5(void);
void doAutoRuns_InputLib_6(void);
void doAutoRuns_InputLib_7(void);
void doAutoRuns_PatchClientLib_0(void);
void doAutoRuns_PatchClientLib_1(void);
void doAutoRuns_PatchClientLib_2(void);
void doAutoRuns_PatchClientLib_3(void);
void doAutoRuns_PatchClientLib_4(void);
void doAutoRuns_PatchClientLib_5(void);
void doAutoRuns_PatchClientLib_6(void);
void doAutoRuns_PatchClientLib_7(void);
void doAutoRuns_PythonLib_0(void);
void doAutoRuns_PythonLib_1(void);
void doAutoRuns_PythonLib_2(void);
void doAutoRuns_PythonLib_3(void);
void doAutoRuns_PythonLib_4(void);
void doAutoRuns_PythonLib_5(void);
void doAutoRuns_PythonLib_6(void);
void doAutoRuns_PythonLib_7(void);
void doAutoRuns_RenderLib_0(void);
void doAutoRuns_RenderLib_1(void);
void doAutoRuns_RenderLib_2(void);
void doAutoRuns_RenderLib_3(void);
void doAutoRuns_RenderLib_4(void);
void doAutoRuns_RenderLib_5(void);
void doAutoRuns_RenderLib_6(void);
void doAutoRuns_RenderLib_7(void);
void doAutoRuns_SoundLib_0(void);
void doAutoRuns_SoundLib_1(void);
void doAutoRuns_SoundLib_2(void);
void doAutoRuns_SoundLib_3(void);
void doAutoRuns_SoundLib_4(void);
void doAutoRuns_SoundLib_5(void);
void doAutoRuns_SoundLib_6(void);
void doAutoRuns_SoundLib_7(void);
void doAutoRuns_UI2Lib_0(void);
void doAutoRuns_UI2Lib_1(void);
void doAutoRuns_UI2Lib_2(void);
void doAutoRuns_UI2Lib_3(void);
void doAutoRuns_UI2Lib_4(void);
void doAutoRuns_UI2Lib_5(void);
void doAutoRuns_UI2Lib_6(void);
void doAutoRuns_UI2Lib_7(void);
void doAutoRuns_UtilitiesLib_0(void);
void doAutoRuns_UtilitiesLib_1(void);
void doAutoRuns_UtilitiesLib_2(void);
void doAutoRuns_UtilitiesLib_3(void);
void doAutoRuns_UtilitiesLib_4(void);
void doAutoRuns_UtilitiesLib_5(void);
void doAutoRuns_UtilitiesLib_6(void);
void doAutoRuns_UtilitiesLib_7(void);
void doAutoRuns_WorldLib_0(void);
void doAutoRuns_WorldLib_1(void);
void doAutoRuns_WorldLib_2(void);
void doAutoRuns_WorldLib_3(void);
void doAutoRuns_WorldLib_4(void);
void doAutoRuns_WorldLib_5(void);
void doAutoRuns_WorldLib_6(void);
void doAutoRuns_WorldLib_7(void);
void doAutoRuns_XLiveLib_0(void);
void doAutoRuns_XLiveLib_1(void);
void doAutoRuns_XLiveLib_2(void);
void doAutoRuns_XLiveLib_3(void);
void doAutoRuns_XLiveLib_4(void);
void doAutoRuns_XLiveLib_5(void);
void doAutoRuns_XLiveLib_6(void);
void doAutoRuns_XLiveLib_7(void);
void doAutoRuns_XRenderLib_0(void);
void doAutoRuns_XRenderLib_1(void);
void doAutoRuns_XRenderLib_2(void);
void doAutoRuns_XRenderLib_3(void);
void doAutoRuns_XRenderLib_4(void);
void doAutoRuns_XRenderLib_5(void);
void doAutoRuns_XRenderLib_6(void);
void doAutoRuns_XRenderLib_7(void);

void doAutoRuns_NNOGameClient_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 0;
	doAutoRuns_GameClientLib_0();
	doAutoRuns_ContentLib_0();
	doAutoRuns_GraphicsLib_0();
	doAutoRuns_HttpLib_0();
	doAutoRuns_InputLib_0();
	doAutoRuns_PatchClientLib_0();
	doAutoRuns_PythonLib_0();
	doAutoRuns_RenderLib_0();
	doAutoRuns_SoundLib_0();
	doAutoRuns_UI2Lib_0();
	doAutoRuns_UtilitiesLib_0();
	doAutoRuns_WorldLib_0();
	doAutoRuns_XLiveLib_0();
	doAutoRuns_XRenderLib_0();
	InitGlobalConfig();
	RegisterProjectVars(); 	_NNOGameClient_AutoRun_SPECIALINTERNAL(); }

void doAutoRuns_NNOGameClient_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 1;
	doAutoRuns_GameClientLib_1();
	doAutoRuns_ContentLib_1();
	doAutoRuns_GraphicsLib_1();
	doAutoRuns_HttpLib_1();
	doAutoRuns_InputLib_1();
	doAutoRuns_PatchClientLib_1();
	doAutoRuns_PythonLib_1();
	doAutoRuns_RenderLib_1();
	doAutoRuns_SoundLib_1();
	doAutoRuns_UI2Lib_1();
	doAutoRuns_UtilitiesLib_1();
	doAutoRuns_WorldLib_1();
	doAutoRuns_XLiveLib_1();
	doAutoRuns_XRenderLib_1();
	OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup();
	OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame(); 	OVERRIDE_LATELINK_AUTORUN_schemes_ControlSchemeOptionInit(); }

void doAutoRuns_NNOGameClient_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 2;
	doAutoRuns_GameClientLib_2();
	doAutoRuns_ContentLib_2();
	doAutoRuns_GraphicsLib_2();
	doAutoRuns_HttpLib_2();
	doAutoRuns_InputLib_2();
	doAutoRuns_PatchClientLib_2();
	doAutoRuns_PythonLib_2();
	doAutoRuns_RenderLib_2();
	doAutoRuns_SoundLib_2();
	doAutoRuns_UI2Lib_2();
	doAutoRuns_UtilitiesLib_2();
	doAutoRuns_WorldLib_2();
	doAutoRuns_XLiveLib_2();
	doAutoRuns_XRenderLib_2();
	Add_Auto_Cmds_NNOGameClient();
}

void doAutoRuns_NNOGameClient_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 3;
	doAutoRuns_GameClientLib_3();
	doAutoRuns_ContentLib_3();
	doAutoRuns_GraphicsLib_3();
	doAutoRuns_HttpLib_3();
	doAutoRuns_InputLib_3();
	doAutoRuns_PatchClientLib_3();
	doAutoRuns_PythonLib_3();
	doAutoRuns_RenderLib_3();
	doAutoRuns_SoundLib_3();
	doAutoRuns_UI2Lib_3();
	doAutoRuns_UtilitiesLib_3();
	doAutoRuns_WorldLib_3();
	doAutoRuns_XLiveLib_3();
	doAutoRuns_XRenderLib_3();
}

void doAutoRuns_NNOGameClient_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 4;
	doAutoRuns_GameClientLib_4();
	doAutoRuns_ContentLib_4();
	doAutoRuns_GraphicsLib_4();
	doAutoRuns_HttpLib_4();
	doAutoRuns_InputLib_4();
	doAutoRuns_PatchClientLib_4();
	doAutoRuns_PythonLib_4();
	doAutoRuns_RenderLib_4();
	doAutoRuns_SoundLib_4();
	doAutoRuns_UI2Lib_4();
	doAutoRuns_UtilitiesLib_4();
	doAutoRuns_WorldLib_4();
	doAutoRuns_XLiveLib_4();
	doAutoRuns_XRenderLib_4();
	Add_Auto_Cmds_NNOGameClient_Later();
}

void doAutoRuns_NNOGameClient_5(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 5;
	doAutoRuns_GameClientLib_5();
	doAutoRuns_ContentLib_5();
	doAutoRuns_GraphicsLib_5();
	doAutoRuns_HttpLib_5();
	doAutoRuns_InputLib_5();
	doAutoRuns_PatchClientLib_5();
	doAutoRuns_PythonLib_5();
	doAutoRuns_RenderLib_5();
	doAutoRuns_SoundLib_5();
	doAutoRuns_UI2Lib_5();
	doAutoRuns_UtilitiesLib_5();
	doAutoRuns_WorldLib_5();
	doAutoRuns_XLiveLib_5();
	doAutoRuns_XRenderLib_5();
}

void doAutoRuns_NNOGameClient_6(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 6;
	doAutoRuns_GameClientLib_6();
	doAutoRuns_ContentLib_6();
	doAutoRuns_GraphicsLib_6();
	doAutoRuns_HttpLib_6();
	doAutoRuns_InputLib_6();
	doAutoRuns_PatchClientLib_6();
	doAutoRuns_PythonLib_6();
	doAutoRuns_RenderLib_6();
	doAutoRuns_SoundLib_6();
	doAutoRuns_UI2Lib_6();
	doAutoRuns_UtilitiesLib_6();
	doAutoRuns_WorldLib_6();
	doAutoRuns_XLiveLib_6();
	doAutoRuns_XRenderLib_6();
	OverrideConfig();
}

void doAutoRuns_NNOGameClient_7(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	giCurAutoRunStep = 7;
	doAutoRuns_GameClientLib_7();
	doAutoRuns_ContentLib_7();
	doAutoRuns_GraphicsLib_7();
	doAutoRuns_HttpLib_7();
	doAutoRuns_InputLib_7();
	doAutoRuns_PatchClientLib_7();
	doAutoRuns_PythonLib_7();
	doAutoRuns_RenderLib_7();
	doAutoRuns_SoundLib_7();
	doAutoRuns_UI2Lib_7();
	doAutoRuns_UtilitiesLib_7();
	doAutoRuns_WorldLib_7();
	doAutoRuns_XLiveLib_7();
	doAutoRuns_XRenderLib_7();
}
extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_NNOGameClient(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_NNOGameClient_0();
	doAutoRuns_NNOGameClient_1();
	doAutoRuns_NNOGameClient_2();
	doAutoRuns_NNOGameClient_3();
	doAutoRuns_NNOGameClient_4();
	doAutoRuns_NNOGameClient_5();
	doAutoRuns_NNOGameClient_6();
	return 0;
}
int MagicAutoRunFunc_File_NNOGameClient(void)
{
	doAutoRuns_NNOGameClient_7();
	return 0;
}
void do_auto_runs(void)
{
	MagicAutoRunFunc_NNOGameClient();
}
void do_auto_runs_file(void)
{
	MagicAutoRunFunc_File_NNOGameClient();
}
extern void _GameClientLib_AutoRun_SPECIALINTERNAL(void);
extern void _ContentLib_AutoRun_SPECIALINTERNAL(void);
extern void _GraphicsLib_AutoRun_SPECIALINTERNAL(void);
extern void _HttpLib_AutoRun_SPECIALINTERNAL(void);
extern void _InputLib_AutoRun_SPECIALINTERNAL(void);
extern void _PatchClientLib_AutoRun_SPECIALINTERNAL(void);
extern void _PythonLib_AutoRun_SPECIALINTERNAL(void);
extern void _RenderLib_AutoRun_SPECIALINTERNAL(void);
extern void _SoundLib_AutoRun_SPECIALINTERNAL(void);
extern void _UI2Lib_AutoRun_SPECIALINTERNAL(void);
extern void _UtilitiesLib_AutoRun_SPECIALINTERNAL(void);
extern void _WorldLib_AutoRun_SPECIALINTERNAL(void);
extern void _XLiveLib_AutoRun_SPECIALINTERNAL(void);
extern void _XRenderLib_AutoRun_SPECIALINTERNAL(void);
void do_special_internal_autoruns(void)
{
	_NNOGameClient_AutoRun_SPECIALINTERNAL();
	_GameClientLib_AutoRun_SPECIALINTERNAL();
	_ContentLib_AutoRun_SPECIALINTERNAL();
	_GraphicsLib_AutoRun_SPECIALINTERNAL();
	_HttpLib_AutoRun_SPECIALINTERNAL();
	_InputLib_AutoRun_SPECIALINTERNAL();
	_PatchClientLib_AutoRun_SPECIALINTERNAL();
	_PythonLib_AutoRun_SPECIALINTERNAL();
	_RenderLib_AutoRun_SPECIALINTERNAL();
	_SoundLib_AutoRun_SPECIALINTERNAL();
	_UI2Lib_AutoRun_SPECIALINTERNAL();
	_UtilitiesLib_AutoRun_SPECIALINTERNAL();
	_WorldLib_AutoRun_SPECIALINTERNAL();
	_XLiveLib_AutoRun_SPECIALINTERNAL();
	_XRenderLib_AutoRun_SPECIALINTERNAL();
};


#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
9
"Add_Auto_Cmds_NNOGameClient" "autogen_magiccommands" 2 "" ""  "" "" 0  0 
"Add_Auto_Cmds_NNOGameClient_Later" "autogen_magiccommands" 4 "" ""  "" "" 0  0 
"InitGlobalConfig" "C:\src\Night\GameClient\NNOGameClient.c" 0 "" ""  "" "" 0  0 
"OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup" "C:\src\Night\GameClient\..\Common\NNOCommon.c" 1 "" ""  "" "" 0  0 
"OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame" "C:\src\Night\GameClient\..\Common\NNOCommon.c" 1 "" ""  "" "" 0  0 
"OVERRIDE_LATELINK_AUTORUN_schemes_ControlSchemeOptionInit" "C:\src\Night\GameClient\NNOGameClient.c" 1 "" ""  "" "" 0  0 
"OverrideConfig" "C:\src\Night\GameClient\NNOGameClient.c" 6 "" ""  "" "" 0  0 
"RegisterProjectVars" "C:\src\Night\GameClient\..\Common\NNOCommon.c" 0 "" ""  "" "" 0  0 
"_NNOGameClient_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" ""  "" "" 0  0 
#endif
