//autogeneratednocheckin  this file is autogenerated by structparser, and includes secondary .c files
//
//
//Beginning forced include of all contents of file C:\src\Night\GameClient\\AutoGen\NNOGameClient_commands_autogen_ExprFuncs.c
//
//
//
//Because this is an executable project, here is where all the crazy web of include
//stuff for exprCodes goes
#include "globaltypes.h"
#include "expressionfunc.h"
#include "ExpressionMinimal.h"
#include "structDefines.h"
#include "mathutil.h"
#define WANT_EXPRCODE_ENUMS_NNOGAMECLIENT
typedef enum exprCodeEnum_AutoGen
{
EXPRCODE_ENUM_PLACEHOLDERZERO,
#include "autogen\NNOGameClient_exprCodes_autogen.h"
} exprCodeEnum_AutoGen;
#undef WANT_EXPRCODE_ENUMS_NNOGAMECLIENT
#define WANT_EXPRCODE_STATICDEFINE_NNOGAMECLIENT
StaticDefineInt enumExprCodeEnum_Autogen[]=
{
	DEFINE_INT
#include "autogen\NNOGameClient_exprCodes_autogen.h"
DEFINE_END
};
#undef WANT_EXPRCODE_STATICDEFINE_NNOGAMECLIENT
#define WANT_EXPRCODE_PROTOTYPES_NNOGAMECLIENT
#include "autogen\NNOGameClient_exprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_NNOGAMECLIENT
#define WANT_EXPRCODE_SWITCH_CASES_NNOGAMECLIENT
ExprFuncReturnVal exprCodeEvaluate_Autogen(MultiVal** args, MultiVal* retval, ExprContext* context, char** errEString, ExprFuncDesc *pFuncDesc, void *pFuncPtr)
{
 switch (pFuncDesc->eExprCodeEnum) {
#include "autogen\NNOGameClient_exprCodes_autogen.h"
}
assertmsgf(0, "Unhandled exprCode case %s", pFuncDesc->pExprCodeName); return 0;
}
#undef WANT_EXPRCODE_SWITCH_CASES_NNOGAMECLIENT
#include "ExpressionEvaluateForAutogenIncluding.c"
//
//
//Ending forced include of all contents of file C:\src\Night\GameClient\\AutoGen\NNOGameClient_commands_autogen_ExprFuncs.c
//
//
//
