//autogeneratednocheckin  this file is autogenerated by structparser
#pragma warning(default:4242)
#ifdef WANT_EXPRCODE_ENUMS_NNOGAMECLIENT
#define WANT_EXPRCODE_ENUMS_GAMECLIENTLIB 1
#include "..\..\CrossRoads\GameClientLib\autogen\GameClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_GAMECLIENTLIB
#define WANT_EXPRCODE_ENUMS_CONTENTLIB 1
#include "..\..\libs\ContentLib\autogen\ContentLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_CONTENTLIB
#define WANT_EXPRCODE_ENUMS_GRAPHICSLIB 1
#include "..\..\libs\GraphicsLib\autogen\GraphicsLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_GRAPHICSLIB
#define WANT_EXPRCODE_ENUMS_HTTPLIB 1
#include "..\..\libs\HttpLib\autogen\HttpLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_HTTPLIB
#define WANT_EXPRCODE_ENUMS_INPUTLIB 1
#include "..\..\libs\InputLib\autogen\InputLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_INPUTLIB
#define WANT_EXPRCODE_ENUMS_PATCHCLIENTLIB 1
#include "..\..\libs\PatchClientLib\autogen\PatchClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_PATCHCLIENTLIB
#define WANT_EXPRCODE_ENUMS_PYTHONLIB 1
#include "..\..\libs\PythonLib\autogen\PythonLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_PYTHONLIB
#define WANT_EXPRCODE_ENUMS_RENDERLIB 1
#include "..\..\libs\Renderers\autogen\RenderLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_RENDERLIB
#define WANT_EXPRCODE_ENUMS_SOUNDLIB 1
#include "..\..\libs\SoundLib\autogen\SoundLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_SOUNDLIB
#define WANT_EXPRCODE_ENUMS_UI2LIB 1
#include "..\..\libs\UI2Lib\autogen\UI2Lib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_UI2LIB
#define WANT_EXPRCODE_ENUMS_UTILITIESLIB 1
#include "..\..\libs\UtilitiesLib\autogen\UtilitiesLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_UTILITIESLIB
#define WANT_EXPRCODE_ENUMS_WORLDLIB 1
#include "..\..\libs\WorldLib\autogen\WorldLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_WORLDLIB
#define WANT_EXPRCODE_ENUMS_XLIVELIB 1
#include "..\..\libs\XLiveLib\autogen\XLiveLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_XLIVELIB
#define WANT_EXPRCODE_ENUMS_XRENDERLIB 1
#include "..\..\libs\XRenderLib\autogen\XRenderLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_ENUMS_XRENDERLIB
#endif //WANT_EXPRCODE_ENUMS_NNOGAMECLIENT
#ifdef WANT_EXPRCODE_STATICDEFINE_NNOGAMECLIENT
#define WANT_EXPRCODE_STATICDEFINE_GAMECLIENTLIB 1
#include "..\..\CrossRoads\GameClientLib\autogen\GameClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_GAMECLIENTLIB
#define WANT_EXPRCODE_STATICDEFINE_CONTENTLIB 1
#include "..\..\libs\ContentLib\autogen\ContentLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_CONTENTLIB
#define WANT_EXPRCODE_STATICDEFINE_GRAPHICSLIB 1
#include "..\..\libs\GraphicsLib\autogen\GraphicsLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_GRAPHICSLIB
#define WANT_EXPRCODE_STATICDEFINE_HTTPLIB 1
#include "..\..\libs\HttpLib\autogen\HttpLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_HTTPLIB
#define WANT_EXPRCODE_STATICDEFINE_INPUTLIB 1
#include "..\..\libs\InputLib\autogen\InputLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_INPUTLIB
#define WANT_EXPRCODE_STATICDEFINE_PATCHCLIENTLIB 1
#include "..\..\libs\PatchClientLib\autogen\PatchClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_PATCHCLIENTLIB
#define WANT_EXPRCODE_STATICDEFINE_PYTHONLIB 1
#include "..\..\libs\PythonLib\autogen\PythonLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_PYTHONLIB
#define WANT_EXPRCODE_STATICDEFINE_RENDERLIB 1
#include "..\..\libs\Renderers\autogen\RenderLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_RENDERLIB
#define WANT_EXPRCODE_STATICDEFINE_SOUNDLIB 1
#include "..\..\libs\SoundLib\autogen\SoundLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_SOUNDLIB
#define WANT_EXPRCODE_STATICDEFINE_UI2LIB 1
#include "..\..\libs\UI2Lib\autogen\UI2Lib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_UI2LIB
#define WANT_EXPRCODE_STATICDEFINE_UTILITIESLIB 1
#include "..\..\libs\UtilitiesLib\autogen\UtilitiesLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_UTILITIESLIB
#define WANT_EXPRCODE_STATICDEFINE_WORLDLIB 1
#include "..\..\libs\WorldLib\autogen\WorldLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_WORLDLIB
#define WANT_EXPRCODE_STATICDEFINE_XLIVELIB 1
#include "..\..\libs\XLiveLib\autogen\XLiveLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_XLIVELIB
#define WANT_EXPRCODE_STATICDEFINE_XRENDERLIB 1
#include "..\..\libs\XRenderLib\autogen\XRenderLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_STATICDEFINE_XRENDERLIB
#endif //WANT_EXPRCODE_STATICDEFINE_NNOGAMECLIENT
#ifdef WANT_EXPRCODE_PROTOTYPES_NNOGAMECLIENT
#define WANT_EXPRCODE_PROTOTYPES_GAMECLIENTLIB 1
#include "..\..\CrossRoads\GameClientLib\autogen\GameClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_GAMECLIENTLIB
#define WANT_EXPRCODE_PROTOTYPES_CONTENTLIB 1
#include "..\..\libs\ContentLib\autogen\ContentLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_CONTENTLIB
#define WANT_EXPRCODE_PROTOTYPES_GRAPHICSLIB 1
#include "..\..\libs\GraphicsLib\autogen\GraphicsLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_GRAPHICSLIB
#define WANT_EXPRCODE_PROTOTYPES_HTTPLIB 1
#include "..\..\libs\HttpLib\autogen\HttpLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_HTTPLIB
#define WANT_EXPRCODE_PROTOTYPES_INPUTLIB 1
#include "..\..\libs\InputLib\autogen\InputLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_INPUTLIB
#define WANT_EXPRCODE_PROTOTYPES_PATCHCLIENTLIB 1
#include "..\..\libs\PatchClientLib\autogen\PatchClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_PATCHCLIENTLIB
#define WANT_EXPRCODE_PROTOTYPES_PYTHONLIB 1
#include "..\..\libs\PythonLib\autogen\PythonLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_PYTHONLIB
#define WANT_EXPRCODE_PROTOTYPES_RENDERLIB 1
#include "..\..\libs\Renderers\autogen\RenderLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_RENDERLIB
#define WANT_EXPRCODE_PROTOTYPES_SOUNDLIB 1
#include "..\..\libs\SoundLib\autogen\SoundLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_SOUNDLIB
#define WANT_EXPRCODE_PROTOTYPES_UI2LIB 1
#include "..\..\libs\UI2Lib\autogen\UI2Lib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_UI2LIB
#define WANT_EXPRCODE_PROTOTYPES_UTILITIESLIB 1
#include "..\..\libs\UtilitiesLib\autogen\UtilitiesLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_UTILITIESLIB
#define WANT_EXPRCODE_PROTOTYPES_WORLDLIB 1
#include "..\..\libs\WorldLib\autogen\WorldLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_WORLDLIB
#define WANT_EXPRCODE_PROTOTYPES_XLIVELIB 1
#include "..\..\libs\XLiveLib\autogen\XLiveLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_XLIVELIB
#define WANT_EXPRCODE_PROTOTYPES_XRENDERLIB 1
#include "..\..\libs\XRenderLib\autogen\XRenderLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_PROTOTYPES_XRENDERLIB
#endif // WANT_EXPRCODE_PROTOTYPES_NNOGAMECLIENT
#ifdef WANT_EXPRCODE_SWITCH_CASES_NNOGAMECLIENT
#define WANT_EXPRCODE_SWITCH_CASES_GAMECLIENTLIB 1
#include "..\..\CrossRoads\GameClientLib\autogen\GameClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_GAMECLIENTLIB
#define WANT_EXPRCODE_SWITCH_CASES_CONTENTLIB 1
#include "..\..\libs\ContentLib\autogen\ContentLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_CONTENTLIB
#define WANT_EXPRCODE_SWITCH_CASES_GRAPHICSLIB 1
#include "..\..\libs\GraphicsLib\autogen\GraphicsLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_GRAPHICSLIB
#define WANT_EXPRCODE_SWITCH_CASES_HTTPLIB 1
#include "..\..\libs\HttpLib\autogen\HttpLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_HTTPLIB
#define WANT_EXPRCODE_SWITCH_CASES_INPUTLIB 1
#include "..\..\libs\InputLib\autogen\InputLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_INPUTLIB
#define WANT_EXPRCODE_SWITCH_CASES_PATCHCLIENTLIB 1
#include "..\..\libs\PatchClientLib\autogen\PatchClientLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_PATCHCLIENTLIB
#define WANT_EXPRCODE_SWITCH_CASES_PYTHONLIB 1
#include "..\..\libs\PythonLib\autogen\PythonLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_PYTHONLIB
#define WANT_EXPRCODE_SWITCH_CASES_RENDERLIB 1
#include "..\..\libs\Renderers\autogen\RenderLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_RENDERLIB
#define WANT_EXPRCODE_SWITCH_CASES_SOUNDLIB 1
#include "..\..\libs\SoundLib\autogen\SoundLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_SOUNDLIB
#define WANT_EXPRCODE_SWITCH_CASES_UI2LIB 1
#include "..\..\libs\UI2Lib\autogen\UI2Lib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_UI2LIB
#define WANT_EXPRCODE_SWITCH_CASES_UTILITIESLIB 1
#include "..\..\libs\UtilitiesLib\autogen\UtilitiesLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_UTILITIESLIB
#define WANT_EXPRCODE_SWITCH_CASES_WORLDLIB 1
#include "..\..\libs\WorldLib\autogen\WorldLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_WORLDLIB
#define WANT_EXPRCODE_SWITCH_CASES_XLIVELIB 1
#include "..\..\libs\XLiveLib\autogen\XLiveLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_XLIVELIB
#define WANT_EXPRCODE_SWITCH_CASES_XRENDERLIB 1
#include "..\..\libs\XRenderLib\autogen\XRenderLib_ExprCodes_autogen.h"
#undef WANT_EXPRCODE_SWITCH_CASES_XRENDERLIB
#endif // WANT_EXPRCODE_SWITCH_CASES_NNOGAMECLIENT
