//This file contains data and prototypes for latelinks. It is autogenerated by StructParser

//autogeneratednocheckin
#include "LateLinkSupport.h"

//Stuff relating to LATELINK_OVERRIDE_ProdSpecificGlobalConfigSetup(), defined in C:\src\Night\GameClient\..\Common\NNOCommon.c
extern void OVERRIDE_LATELINK_ProdSpecificGlobalConfigSetup(void);
typedef void ProdSpecificGlobalConfigSetup_LATELINK_FPTYPE_INTERNAL(void);
extern ProdSpecificGlobalConfigSetup_LATELINK_FPTYPE_INTERNAL *ProdSpecificGlobalConfigSetup_LATELINK_FP;
extern char *ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_ProdSpecificGlobalConfigSetup(void)
{
	ProdSpecificGlobalConfigSetup_LATELINK_FP = OVERRIDE_LATELINK_ProdSpecificGlobalConfigSetup;
	TestLateLinkArgString(&ProdSpecificGlobalConfigSetup_LATELINK_ARGSTRING, "void ", "ProdSpecificGlobalConfigSetup");
}

//Stuff relating to LATELINK_OVERRIDE_isValidRegionTypeForGame(), defined in C:\src\Night\GameClient\..\Common\NNOCommon.c
extern bool OVERRIDE_LATELINK_isValidRegionTypeForGame(U32 arg0);
typedef bool isValidRegionTypeForGame_LATELINK_FPTYPE_INTERNAL(U32 arg0);
extern isValidRegionTypeForGame_LATELINK_FPTYPE_INTERNAL *isValidRegionTypeForGame_LATELINK_FP;
extern char *isValidRegionTypeForGame_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_isValidRegionTypeForGame(void)
{
	isValidRegionTypeForGame_LATELINK_FP = OVERRIDE_LATELINK_isValidRegionTypeForGame;
	TestLateLinkArgString(&isValidRegionTypeForGame_LATELINK_ARGSTRING, "bool U32 ", "isValidRegionTypeForGame");
}

//Stuff relating to LATELINK_OVERRIDE_schemes_ControlSchemeOptionInit(), defined in C:\src\Night\GameClient\NNOGameClient.c
extern void OVERRIDE_LATELINK_schemes_ControlSchemeOptionInit(void* arg0);
typedef void schemes_ControlSchemeOptionInit_LATELINK_FPTYPE_INTERNAL(void* arg0);
extern schemes_ControlSchemeOptionInit_LATELINK_FPTYPE_INTERNAL *schemes_ControlSchemeOptionInit_LATELINK_FP;
extern char *schemes_ControlSchemeOptionInit_LATELINK_ARGSTRING;
static void OVERRIDE_LATELINK_AUTORUN_schemes_ControlSchemeOptionInit(void)
{
	schemes_ControlSchemeOptionInit_LATELINK_FP = OVERRIDE_LATELINK_schemes_ControlSchemeOptionInit;
	TestLateLinkArgString(&schemes_ControlSchemeOptionInit_LATELINK_ARGSTRING, "void const char * ", "schemes_ControlSchemeOptionInit");
}


#ifdef THIS_SYMBOL_IS_NOT_DEFINED
PARSABLE
3
1 "ProdSpecificGlobalConfigSetup" "void"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "C:\src\Night\GameClient\..\Common\NNOCommon.c" 23 0 "void " 
1 "isValidRegionTypeForGame" "bool"  "U32"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "C:\src\Night\GameClient\..\Common\NNOCommon.c" 160 1 "bool U32 " 
1 "schemes_ControlSchemeOptionInit" "void"  "void*"  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  ""  "C:\src\Night\GameClient\NNOGameClient.c" 72 0 "void const char * " 
#endif
