#ifndef CRYPTIC_PATCHMIRRORING_OPT_H
#define CRYPTIC_PATCHMIRRORING_OPT_H

typedef MemLog MemLog;

AUTO_ENUM;
typedef enum UpdateStates {
	UPDATE_NOTIFYME_START = 0,
	UPDATE_LISTING_START,
	UPDATE_SERVERDB_VIEW,
	UPDATE_SERVERDB_FILE,
	UPDATE_SERVERDB_DONE,
	UPDATE_PROJECT_VIEW,
	UPDATE_PROJECT_FILE,
	UPDATE_PROJECT_DONE,
	UPDATE_CONFIGS_RELOAD,
	UPDATE_MANIFEST_VIEW,
	UPDATE_MANIFEST_FILE,
	UPDATE_MANIFEST_LOAD_START,
	UPDATE_MANIFEST_LOAD_WAIT,
	UPDATE_MANIFEST_PRUNE_CHECKIN,
	UPDATE_MANIFEST_CHECKIN_VIEW,
	UPDATE_MANIFEST_CHECKIN_FILE,
	UPDATE_MANIFEST_CHECKIN_DONE,
	UPDATE_MANIFEST_COPY_START,
	UPDATE_MANIFEST_COPY_WAIT,

	UPDATE_STATE_COUNT
} UpdateStates;

// Debugging memlog.
extern MemLog updatememlog;

// Current update step.
extern UpdateStates g_update_state;

// Switch to a new state; use patchmirroringSwitchStatef().
void patchmirroringSwitchStatef_dbg(UpdateStates new_state, FORMAT_STR const char *format, ...);

#endif  // CRYPTIC_PATCHMIRRORING_OPT_H
